version: '3.8'
services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file:
      - fast_survey/.env
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - fast_survey/.env

  fast_survey:
    container_name: fast_survey
    build: .
    command: uvicorn fast_survey.main:app --host 0.0.0.0 --reload
    restart: always
    volumes:
    - ./fast_survey:/app/fast_survey
    ports:
      - 8000:8000
    depends_on:
      - mongo
